"""Auto-import all fetcher modules so their @register_fetcher decorators run."""
from driftwatch.fetchers import (
    s3,
    ec2,
    rds,
    iam,
    lambda_,
    sns,
    sqs,
    cloudwatch,
    ecs,
    dynamodb,
    elb,
    secretsmanager,
    kinesis,
    stepfunctions,
    cloudtrail,
    elasticache,
    route53,
)

__all__ = [
    "s3",
    "ec2",
    "rds",
    "iam",
    "lambda_",
    "sns",
    "sqs",
    "cloudwatch",
    "ecs",
    "dynamodb",
    "elb",
    "secretsmanager",
    "kinesis",
    "stepfunctions",
    "cloudtrail",
    "elasticache",
    "route53",
]
